apiVersion: apps/v1
kind: Deployment
metadata:
  name: wingspan-quiz
  labels:
    app: wingspan-quiz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wingspan-quiz
  template:
    metadata:
      labels:
        app: wingspan-quiz
    spec:
      containers:
      - name: wingspan-quiz
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
